

const routes = {
  'firstPage':{
    'name':'fisrtPage',
    'path':'/'
  },
  'student-home':{
    'name':'student-home',
    'path':'student-home'
  },
  'professor-home':{
    'name':'professor-home',
    'path':'professor-home'
  }
  ,
  'checkAuthenticated':{
    'name':'checkAuthenticated',
    'path':'check-authenticated'
  },
  'login':{
    'name':'login',
    'path':'login'
  },
  'register':{
    'name':'register',
    'path':'register'
  },
  'splachScreen':{
    'name':'splash',
    'path':'splash'
  },
  'appPresentation':{
    'name':'app-presentation',
    'path':'app-presentation'
  },
  'chatPage':
  {
    'name':'chat',
    'path':'chat'
  }
};